config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  get 'admin' => 'admin#index'
  
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'admin/index'

  resources :users

  root 'sessions#new'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  has_many :resumes, dependent: :destroy
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  
  private
    def ensure_an_admin_remains
        if User.count.zero?
          raise "Can't delete last user"
        end
    end
    
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_filter :authorize
  
  def index                           
    @resumes = Resume.where('user_id = ?',session[:user_id])
    
    @total_resumes = Resume.where("resumes.user_id = ?", session[:user_id]).count
    
    @user_name = session[:fname] + " " + session[:lname]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authorize
  
  protected
  
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
  
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  skip_before_action :authorize
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @user_name = session[:fname] + " " + session[:lname]
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to admin_path, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:objective, :skills, :experience, :education, :user_id, :style_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:fname] = user.fname
      session[:lname] = user.lname
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:lname)
    
    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @users}
     end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: "User #{@user.fname} #{@user.lname} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.fname} #{@user.lname} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.fname} #{@user.lname} deleted."
    rescue Exception => e
      flash[:notice] = e.message
    end
    
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
<div class="container-fluid">
	<h1>Welcome <%= @user_name %></h1><br><br>
	<h4>It's <%= Time.now.strftime("%I:%M %p on %m/%d/%Y") %><br>
	You have <%= pluralize(@total_resumes, "resume") %> available to edit.</h4>
	 
	<% if @total_resumes > 0 %>
		<table class="table table-striped">
		  <thead>
		    <tr>
		      <th>Objective</th>
			  <th>Skills</th>
			  <th>Experience</th>
			  <th>Education</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		
		  <tbody>
			<% @resumes.each do |resume| %>
			  <tr>
		        <td><%= resume.objective %></td>
		        <td><%= resume.skills %></td>
		        <td><%= resume.experience %></td>
		        <td><%= resume.education %></td>
		        <td><%= link_to 'Show', resume %></td>
		        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
		        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	<% end %>
	
	<p><%= link_to 'New Resume', new_resume_path %></p>
	<p><%= link_to 'Logout', logout_path, method: :delete %></p>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RenovateMyResume</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resumes/_form.html.erb
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
<div class="container-fluid">
	<%= form_for(@resume) do |f| %>
	  <% if @resume.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>
	
	      <ul>
	      <% @resume.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :objective %><br>
	    <%= f.text_area :objective %>
	  </div>
	  <div class="field">
	    <%= f.label :skills %><br>
	    <%= f.text_area :skills %>
	  </div>
	  <div class="field">
	    <%= f.label :experience %><br>
	    <%= f.text_area :experience %>
	  </div>
	  <div class="field">
	    <%= f.label :education %><br>
	    <%= f.text_area :education %>
	  </div>
	  <%= f.hidden_field :user_id, :value => session[:user_id] %>
	  <%= hidden_field_tag 'selected', 'none'  %>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', admin_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Objective</th>
      <th>Skills</th>
      <th>Experience</th>
      <th>Education</th>
      <th>User</th>
      <th>Style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.objective %></td>
        <td><%= resume.skills %></td>
        <td><%= resume.experience %></td>
        <td><%= resume.education %></td>
        <td><%= resume.user_id %></td>
        <td><%= resume.style_id %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/resumes/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
<script type="text/javascript">
	$(document).ready(function(){
		$("#purple").click(function(){
			$("#background-style").css({
				"background-image": "url(<%= asset_path('purple_background.jpg') %>)",
				"background-repeat": "no-repeat"
			});

		});
	$("#blue").click(function(){
			$("#background-style").css({
				"background-image": "url(<%= asset_path('blue_background.jpg') %>)",
				"background-repeat": "no-repeat"
			});

		});
		$("#green").click(function(){
			$("#background-style").css({
				"background-image": "url(<%= asset_path('green_background.png') %>)",
				"background-repeat": "no-repeat"
			});

		});
	});
</script>
<div class="container-fluid text-center" style="position:relative; height: 768px; width: 1366px;" >
	
		<h1>View Resume</h1>
		<h2>Select a Style</h2><br><br>
		<form action="" style="align-text:center">
			<input type="radio" name="styles" id="purple" value="purple">Faded Purple &nbsp&nbsp
			<input type="radio" name="styles" id="blue" value="blue">Faded Blue &nbsp&nbsp
			<input type="radio" name="styles" id="green" value="green">Faded Green<br><br><br>
		</form>
		<p id="notice"><%= notice %></p>
	<div id="background-style" style="text-align: left; margin: auto; width: 40%; height: 80%; padding: 10px; box-shadow: 15px 15px #555555;">
		  <h2><strong><%= @user_name %></strong></h2>
		  <strong>_________________________________________________________</strong>
		  
		  <h3>Objective:</h3>
		  <p><%= @resume.objective %></p><br>
		
		
		  <h3>Skills:</h3>
		  <h4><%= @resume.skills %></h4><Br>
		
		  <h3>Experience:</h3>
		  <p><%= @resume.experience %></p><br>
		
		  <h3>Education:</h3>
		  <p><%= @resume.education %></p><br>
		  
	</div><br><br>
		  <%= link_to 'Edit', edit_resume_path(@resume) %> |
		  <%= link_to 'Back', admin_path %>	
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
	<% if notice %>
	<p id="notice"><%= notice %></p>
	<% end %>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>